branch-defaults:
  master:
    environment: sskts-api-development
    group_suffix: null
global:
  application_name: sskts-api
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ap-northeast-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
