version: 2
jobs:
  build:
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: node version
          command: node -v
      - run:
          name: npm version
          command: npm -v
      # - run:
      #     name: Update npm
      #     command: 'sudo npm install -g npm@latest'
      - run:
          name: configure npm for private modules
          command: |
            npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm whoami
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install npm packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: compile typescript
          command: npm run build
  test:
    docker:
      - image: circleci/node:latest
      - image: circleci/mongo:3.2
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: run npm test
          command: npm test
      # - run:
      #     name: Generate code coverage
      #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests
      # - store_artifacts:
      #     path: coverage
      #     prefix: coverage
  doc:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Generate docs
          command: |
            npm run build
            npm run doc
  deploy2development:
    docker:
      - image: circleci/node:8.4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: deploy to azure webapps development
          command: |
            git remote add origin ${DEPLOY_TARGET_REPOSITORY_DEVELOPMENT}
            # git config --global user.email "{email}"
            # git config --global user.name "{username}"
            # git add .
            # git commit -am "Circle CI #$CIRCLE_BUILD_NUM"
            git push origin master 
# Used for orchestrating all jobs.
workflows:
  version: 2

  build-test-doc:
    jobs:
      - build
      - test:
          requires:
            - build
      - doc:
          requires:
            - test
      - deploy2development:
          requires:
            - doc
          filters:
            branches:
              only: develop
      # - deploy:
      #     requires:
      #       - doc
      #     filters:
      #       branches:
      #         only: master

